### ISSUE TITLE
Heating Issue

### ISSUE THREAD

**Issue by Dwarklin** [Hexuar/VoxelSmith#1]
When i throw iron ingots on magma block they are not heating.

What do i do?

**Comment by Hexuar** [comment]
Heating is a process that takes a little while. If you pick the ingots back up again, do you see the temperature statistic when hovering over the item?

**Comment by Dwarklin** [comment]
I don't see any heat statistic.
I don't even get the advancement for dropping ingot on magma block

also does datapack work on 1.20.1?

**Comment by Hexuar** [comment]
This datapack specifically requires 1.20.2+

**Comment by Dwarklin** [comment]
I figured it out yesterday that i had to be on 1.20.4.
Thanks for your help now it works.

Also amazing datapack i love it
