### ISSUE TITLE
Textures not showing

### ISSUE THREAD

**Issue by LivyLives** [Hexuar/VoxelSmith#2]
I am running the datapack on a server, for which I have a few resource packs in use. All the functionality seems to be in place, but there are no custom textures present. I cant find any resource pack in the in game menu, and cant see ant resources in the downloaded zip file.

Other than this, your datapack seems incredible, and just what I have always wanted for a vanilla+ smithing experience in minecraft :)

**Comment by Hexuar** [comment]
You can download the resourcepack on modrinth, it's just a little hidden unfortunately. Once on the versions page, click on the latest version, and you'll find it there.
