### ISSUE TITLE
Add wiki page on how to add custom materials

### ISSUE THREAD

**Issue by TheEmeraldBee** [Hexuar/VoxelSmith#4]
I've been messing a lot with adding custom materials, following your code, but I must be missing something, as it isn't working for me. I've gotten it to a point that it logs all of the info that the materials and recipes were added, but when tossing the item onto either an anvil or polished andesite, nothing happens.

**Comment by TheEmeraldBee** [comment]
And of course like 5 minutes after writing this, I finally figured it out. Do you need someone to write this wiki page for you? If so, I'm happy to do it.

**Comment by Hexuar** [comment]
Hi there! The wiki is currently slightly outdated. 

I'll update it and add a custom material page soon. However, if you want to help. You can definitely write the custom material page, and I'll review it later.

Don't hesitate to ask about any other questions you've got and happy modding!
